#include <stdio.h>

// \x1b[31m = red
// \x1b[34m = blue
// \x1b[0m  = reset color
int main() {
	printf("In the fullness of time \x1b[31mMS-DOS\x1b[0m begat \x1b[31mWindows\x1b[0m. And this is the lineage of \x1b[31mWindows\x1b[0m: \x1b[31mCP/M\x1b[0m begat \x1b[31mQDOS\x1b[0m. \x1b[31mQDOS\x1b[0m begat \x1b[31mDOS 1.0\x1b[0m. \x1b[31mDOS 1.0\x1b[m begat \x1b[31mDOS 2.0\x1b[m by way of \x1b[31mUnix\x1b[0m. \x1b[31mDOS 2.0\x1b[m begat \x1b[31mWindows 3.11\x1b[m by way of \x1b[31mPARC\x1b[0m and \x1b[31mMacintosh\x1b[0m. \x1b[34mIBM\x1b[0m and \x1b[34mMicrosoft\x1b[0m begat \x1b[31mOS/2\x1b[0m, who begat \x1b[31mWindows NT\x1b[0m and \x1b[31mWarp\x1b[0m, the lost OS of lore. \x1b[31mWindows 3.11\x1b[0m begat \x1b[31mWindows 95\x1b[0m after triumphing over \x1b[31mMacintosh\x1b[0m in a mighty Battle of Licences. \x1b[31mWindows NT\x1b[0m begat \x1b[31mNT 4.0\x1b[0m by way of \x1b[31mWindows 95\x1b[0m. \x1b[31mNT 4.0\x1b[0m begat \x1b[31mNT 5.0\x1b[0m, the OS also called \x1b[31mWindows 2000\x1b[0m, The \x1b[34mMillenium Bug\x1b[0m, \x1b[34mDoomsday\x1b[0m, \x1b[34mArmageddon\x1b[0m, The End Of All Things.\n");
	printf("Now it came to pass that \x1b[34mMicrosoft\x1b[0m had waxed great and mighty among the \x1b[34mMicrochip Corporations\x1b[0m; mighter than any of the \x1b[34mMainframe Corporations\x1b[0m before it had it waxed. And \x1b[34mGates\x1b[0m heart was hardened, and he swore unto his Customers and their Engineers the words of this curse:\n");
	printf("\"Children of \x1b[34mvon Neumann\x1b[0m, hear me. \x1b[34mIBM\x1b[0m and the \x1b[34mMainframe Corporations\x1b[0m bound thy forefathers with grave and perilous Licences, such that ye cried unto the spirits of \x1b[34mTuring\x1b[0m and \x1b[34mvon Neumann\x1b[0m for deliverance. Now I say unto ye: I am greater than any Corporation before me. Will I loosen your Licences? Nay, I will bind thee with Licences twice as grave and ten times more perilous than my forefathers. I will engrave my Licence on thy heart and write my Serial Number upon thy frontal lobes. I will bind thee to the \x1b[31mWindows Platform\x1b[0m with cunning artifices and with devious schemes. I will bind thee to the \x1b[34mIntel Chipset\x1b[0m with crufty code and with gnarly APIs. I will capture and enslave thee as no generation has been enslaved before. And wherefore will ye cry then unto the spirits of \x1b[34mTuring\x1b[0m , and \x1b[34mvon Neumann\x1b[0m , and \x1b[34mMoore\x1b[0m? They cannot hear ye. I am become a greater Power than they. Ye shall cry only unto me, and shall live by my mercy and my wrath. I am the \x1b[34mGates\x1b[0m of Hell; I hold the portal to \x1b[34mMSNBC\x1b[0m and the keys to the Blue Screen of Death. Be ye afraid; be ye greatly afraid; serve only me, and live.\"\n");
	printf("And the people were cowed in terror and gave homage to \x1b[34mMicrosoft\x1b[0m, and endured the many grave and perilous trials which the \x1b[31mWindows platform\x1b[0m and its greatly bogacious Licence forced upon them. And once again did they cry to \x1b[34mTuring\x1b[0m and \x1b[34mvon Neumann\x1b[0m and \x1b[34mMoore\x1b[0m for a deliverer , but none was found equal to the task until the birth of \x1b[31mLinux\x1b[0m.");
	printf("These are the generations of \x1b[31mLinux\x1b[0m:\n");
	printf("\x1b[34mSAGE\x1b[0m begat \x1b[34mARPA\x1b[0m, which begat \x1b[34mTCP/IP\x1b[0m, and \x1b[34mAloha\x1b[0m, which begat \x1b[34mEthernet\x1b[0m. \x1b[34mBell\x1b[0m begat \x1b[34mMultics\x1b[0m, which begat C, which begat \x1b[31mUnix\x1b[0m. \x1b[31mUnix\x1b[0m and \x1b[34mTCP/IP\x1b[0m begat Internet , which begat the \x1b[34mWorld Wide Web\x1b[0m. \x1b[31mUnix\x1b[0m begat \x1b[34mRMS\x1b[0m, father of the great \x1b[34mGNU\x1b[0m, which begat the \x1b[34mLibraries\x1b[0m and \x1b[34mEmacs\x1b[0m, chief of the Utilities. In the days of the Web, Internet and Ethernet begat the \x1b[34mIntranet LAN\x1b[0m, which rose to renown among all Corporations and prepared the way for the \x1b[34mPenguin\x1b[0m. And \x1b[34mLinus\x1b[0m and the Web begat the Kernel through \x1b[31mUnix\x1b[0m. The Kernel, the Libraries and the Utilities together are the Distribution , the one \x1b[34mPenguin\x1b[0m in many forms , forever and ever praised.\n");
	return 0;
}
